[package]
name = "bevy_iced"
version = "0.2.1"
edition = "2021"
description = "Iced integration for Bevy"
authors = ["tasgon <tasgon_@outlook.com>"]
license = "MIT OR Apache-2.0"
keywords = ["bevy", "iced", "ui", "game", "gui"]
homepage = "https://github.com/tasgon/bevy_iced"
repository = "https://github.com/tasgon/bevy_iced"
documentation = "https://docs.rs/bevy_iced"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_app = "0.9"
bevy_derive = "0.9"
bevy_ecs = "0.9"
bevy_input = "0.9"
bevy_render = "0.9"
bevy_utils = "0.9"
bevy_window = "0.9"

iced_wgpu = "0.7"
iced_native = "0.7"

[dev-dependencies]
bevy = "0.9"
rand = "0.8"