[package]
name = "bevy_iced"
version = "0.3.0"
edition = "2021"
description = "Iced integration for Bevy"
authors = ["tasgon <me@tas.sh>"]
license = "MIT OR Apache-2.0"
keywords = ["bevy", "iced", "ui", "game", "gui"]
homepage = "https://github.com/tasgon/bevy_iced"
repository = "https://github.com/tasgon/bevy_iced"
documentation = "https://docs.rs/bevy_iced"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
touch = []

[dependencies]
bevy_app = "0.11"
bevy_derive = "0.11"
bevy_ecs = "0.11"
bevy_input = "0.11"
bevy_math = "0.11"
bevy_render = "0.11"
bevy_utils = "0.11"
bevy_window = "0.11"

iced = { git = "https://github.com/iced-rs/iced.git", rev = "5dd9234" }
iced_core = { git = "https://github.com/iced-rs/iced.git", rev = "5dd9234" }
iced_graphics = { git = "https://github.com/iced-rs/iced.git", rev = "5dd9234" }
iced_runtime = { git = "https://github.com/iced-rs/iced.git", rev = "5dd9234" }
iced_wgpu = { git = "https://github.com/iced-rs/iced.git", rev = "5dd9234" }
iced_winit = { git = "https://github.com/iced-rs/iced.git", rev = "5dd9234" }

[dev-dependencies]
bevy = "0.11"
rand = "0.8"