[package]
name = "bevy_iced"
version = "0.1.0"
edition = "2021"
description = "Iced integration for Bevy"
authors = ["tasgon <tasgon_@outlook.com>"]
license = "MPL-2.0"
keywords = ["bevy", "iced", "ui", "game", "gui"]
homepage = "https://github.com/tasgon/bevy_iced"
repository = "https://github.com/tasgon/bevy_iced"
documentation = "https://docs.rs/bevy_iced"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6"
iced_wgpu = { git = "https://github.com/iced-rs/iced.git", branch = "0.4" }
iced_native = { git = "https://github.com/iced-rs/iced.git", branch = "0.4" }

[dev-dependencies]
rand = "0.8"
bevy-inspector-egui = "0.8"